name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: windows-2016
    steps:

    - name: Set up Go 1.14.4
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.4
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -race .
